# 
# kjstomization custom resource to load resources located in the apps folder
#
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 11m0s
  path: ./app/homelab
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system