apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart: external-secrets
  version: "0.14.4"
  interval: 5h
  sourceRef: 
    kind: HelmRepository
    name: external-secrets
    
