apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmChart
metadata:
  name: external-secrets-chart
  namespace: external-secret
spec:
  chart: external-secrets
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: OCIRepository
    name: external-secrets
  interval: 1h