apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: 0.9.11  # or latest stable
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system  # matches your HelmRepository namespace
  interval: 5m
  values:
    installCRDs: true
