apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart: 
    spec: 
      chart: external-secrets
      version: "0.14.4"
      interval: 5h # this is for checking of a new chart
      sourceRef: 
        kind: HelmRepository
        name: nginx
  releaseName: external-secrets
  targetNamespace: external-secrets
  interval: 1h #this is fo drifting of the helm created resources
  values:
      installCRDs: true

