apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      version: "0.14.4"  # Specify the version you want to install
      sourceRef:
        kind: HelmRepository
        name: external-secrets  # This should match the name of your HelmRepository
        namespace: external-secrets  # Namespace where the HelmRepository is created
  interval: 1h  # Interval for reconciling the HelmRelease
  targetNamespace: external-secrets  # Namespace where the chart will be installed
  values:
    installCRDs: true  # Install CRDs