apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  chart:
    spec:
      chart: external-secrets
      version: "0.14.x"
      sourceRef:
        kind: OCIRepository
        name: external-secrets
        namespace: external-secrets
  values:
    installCRDs: true
    serviceAccount:
      create: true
      name: "external-secrets"
    webhook:
      port: 9443
      create: true
      certManager:
        enabled: true