apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: flux-system  # Change this!
spec:
  url: https://charts.external-secrets.io
  interval: 10m
