apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  url: oci://ghcr.io/nginxinc/charts
  type: oci
  interval: 5m