apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 1h
  url: oci://ghcr.io/external-secrets/charts
  ref:
    tag: external-secrets-0.9.5
  provider: generic