apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system  # or other namespace where you want to install it
spec:
  interval: 1h
  chart:
    spec:
      chart: external-secrets
      version: "0.9.x"  # Use the latest stable version
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    # Add any custom values here if needed