apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password.svc.cluster.local:8080
      vaults:
        homelab: 0  # ✅ Correct: map with vault name and integer value
      auth:
        secretRef:
          connectTokenSecretRef:
            name: op-credentials
            key: 1password-credentials.json
            namespace: 1password
