apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password.svc.cluster.local:8080
      vaults:
        homelab: {}  # ✅ Correct: vault name mapped to empty object
      auth:
        connectToken:
          secretRef:
            name: onepassword-credentials  # ✅ Your secret name
            key: token                     # ✅ Key inside the secret
            namespace: 1password          # Namespace where the secret exists
