apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: n8n
  namespace: n8ns
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-secret
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        N8N_ENCRYPTION_KEY: '{{ .n8n_encryption_key }}'
      engineVersion: v2
      mergePolicy: Replace
  dataFrom:
    - extract:
        key: n8n
