apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname n8n
  namespace: &namespace selfhosted
spec:
  targetNamespace: *namespace
  interval: 30m
  timeout: 5m
  path: "./kubernetes/infastructure/base/n8n"  # Fixed path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: onepassword-store
      namespace: external-secrets
    - name: volsync
      namespace: system
  components:
    - ../../../../components/volsync  # Verify this path!
  # Use Kustomize-native substitutions if needed
  configMapGenerator:
    - name: app-config
      literals:
        - APP=n8n
        - APP_UID=1000
        - APP_GID=1000
        - VOLSYNC_CAPACITY=5Gi