apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql-database
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.6.0
      sourceRef:
        kind: HelmChart
        name: postgresql-chart
        namespace: flux-system
      interval: 5m
  values:
    auth:
      enablePostgresUser: false
      username: admin
      existingSecret: postgresql-secrets
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql
      resources:
        requests:
          memory: 50Mi
          cpu: 25m
        limits:
          memory: 200Mi
