apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql-database
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.6.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    auth:
      enablePostgresUser: false
      username: admin
      existingSecret: postgresql-secrets
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql
      resources:
        requests:
          memory: 50Mi
          cpu: 25m
        limits:
          memory: 200Mi
      # Add security context to fix permissions
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
    # Enable volume permissions init container
    volumePermissions:
      enabled: true
    # Increase timeout for installation
    timeout: 600s