apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql-database
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 16.6.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
        namespace: flux-system
  values:
    auth:
      enablePostgresUser: true 
      username: admin
      existingSecret: postgresql-secrets
      secretKeys:
        adminPasswordKey: password
        postgresPasswordKey: password  # Add this line
    primary:
      persistence:
        enabled: true
        existingClaim: postgresql
      resources:
        requests:
          memory: 50Mi
          cpu: 25m
        limits:
          memory: 200Mi
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
    volumePermissions:
      enabled: true
    timeout: 600s