apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openebs-linkding
  hostPath:
    path: /mnt/data/postgresql 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: postgresql-database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-linkding
  resources:
    requests:
      storage: 512Mi