apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-oci
  namespace: flux-system
spec:
  #interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts
  type: oci
