apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-linkding
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust size as needed
  storageClassName: openebs-linkding
