apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-linkding
provisioner: openebs.io/local
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding
  namespace: linkding
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: openebs-linkding
  volumeMode: Filesystem
  selector:
    matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
          - ip-10-0-1-132.ec2.internal
