---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    provider: 
      name: pihole
    env:
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: *secret
            key: EXTERNAL_DNS_PIHOLE_PASSWORD
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    extraArgs:
      - "--pihole-server=http://10.0.0.254"
      - "--ignore-ingress-tls-spec"
      - "--ingress-class=internal"
    policy: sync
    sources: ["ingress", "service"]
    triggerLoopOnEvent: true
    domainFilters: ["rafaribe.com"]
    serviceMonitor:
      enabled: true