# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mojo2600
  namespace: flux-system
spec:
  interval: 12h
  url: https://mojo2600.github.io/pihole-kubernetes/