apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: selfhosted

resources:
  - "app"  # This references the app directory and its kustomization

commonLabels:
  app.kubernetes.io/name: n8n
  app.kubernetes.io/instance: n8n

configMapGenerator:
  - name: app-config
    literals:
      - APP=n8n
      - APP_UID=1000
      - APP_GID=1000
      - VOLSYNC_CAPACITY=5Gi