apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: whoami
  namespace: whoami
spec:
  interval: 10m 
  chart:
    spec:
      chart: whoami
      version: 1.6.0
      sourceRef: 
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      type: loadbalancer 