---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: one-password
spec:
  interval: 12h
  maxHistory: 3
  chart:
    spec:
      chart: connect
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: connect-helm-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    connect:
      annotations:
        reloader.stakater.com/auto: "true"
      credentialsName: onepassword-connect-secret
      api:
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            memory: 100Mi
      sync:
        resources:
          requests:
            cpu: 5m
            memory: 10Mi
          limits:
            memory: 100Mi