apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  chart:
    spec:
      chart: pgadmin4
      version: "1.10.0"  # Check for latest version
      sourceRef:
        kind: HelmRepository
        name: runix
        namespace: flux-system
  values:
    env:
      email: "{{ .ADMIN_EMAIL }}"
      password: "{{ .POSTGRES_SUPER_PASS }}"
    persistence:
      enabled: true
      size: 1Gi