apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: "3.7.3"  # Use latest version from search results
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    image:
      repository: docker.io/dpage/pgadmin4
      tag: "9.2@sha256:52cb72a9e3da275324ca0b9bb3891021366d501aad375db34584a7bca8ce02ff"
    
    service:
      main:
        enabled: true
        type: ClusterIP
        ports:
          http:
            enabled: true
            port: 80
            targetPort: 80
    
    ingress:
      main:
        enabled: true
        hosts:
          - host: pgadmin.zinn.ca
            paths:
              - path: /
                pathType: Prefix
        tls: []
    
    envFrom:
      - secretRef:
          name: pgadmin-secret
    
    persistence:
      config:
        enabled: true
        storageClass: "n8n-storage"
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: /var/lib/pgadmin