apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
spec:
  refreshInterval: 1h  # Recommended for automatic refreshes
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pgadmin-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app: pgadmin
      data:
        PGADMIN_DEFAULT_EMAIL: "{{ .ADMIN_EMAIL | toString }}"
        PGADMIN_DEFAULT_PASSWORD: "{{ .POSTGRES_SUPER_PASS | toString }}"
  dataFrom:
    - extract:
        key: admin-user
    - extract:
        key: cloudnative-pg-superuser