apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pgadmin-sc
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: pgadmin
  labels:
    app: pgadmin
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pgadmin-sc
  hostPath:
    path: /var/lib/pgadmin # This will be stored on the host machine running KIND

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: pgadmin
  labels:
    app: pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: pgadmin-sc

