---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgadmin-pv
  namespace: pgadmin
  labels:
    app: pgadmin
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: n8n-storage
  hostPath:
    path: /var/lib/pgadmin # This will be stored on the host machine running KIND

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: pgadmin
  labels:
    app: pgadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: n8n-storage

