apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bankapp
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: Zll1Zy9CcXB0VXVLUEVlZTUyTTRrY3JLYW9FWWl5K2FqVDY2b1FYNVFWRT0=
  SPRING_DATASOURCE_PASSWORD: Zll1Zy9CcXB0VXVLUEVlZTUyTTRrY3JLYW9FWWl5K2FqVDY2b1FYNVFWRT0=

