---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring-system
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana
      version: 8.10.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    grafana.ini:
      analytics:
        check_for_updates: false
        check_for_plugin_updates: false
        reporting_enabled: false
      news:
        news_feed_enabled: false

    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: default
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            isDefault: true  # ✅ Only one default datasource
            url: http://kube-prometheus-stack-prometheus.monitoring-system.svc.cluster.local:9090
            access: proxy
          - name: Loki
            type: loki
            url: http://loki-gateway.monitoring-system.svc.cluster.local
            jsonData:
              maxLines: 250

    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/whitelist-source-range: |
          10.244.0.0/16,10.10.10.0/24,192.168.50.0/24,192.168.10.0/24,192.168.200.0/24
      pathType: Prefix
      hosts:
        - grafana.jonatech.online  # ✅ Replaced variable with a valid domain
      tls:
        - hosts:
            - grafana.jonatech.online
          secretName: grafana.jonatech.online-tls

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi  # ✅ Increased to prevent crashes

    admin:
      existingSecret: grafana-secret
      userKey: gf_security_admin_user
      passwordKey: gf_security_admin_password
    serviceMonitor:
      enabled: true
    rbac:
      pspEnabled: false
