# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.26.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring-system 
    labels:
        app.kubernetes.io/name: grafana
type: Opaque
stringData:
    gf_security_admin_user: ENC[AES256_GCM,data:HXWlrMthMQ==,iv:krnoPlP4hL07CjO8PTg+VQSFvzVsTAr+lARM8FSKUn4=,tag:XbVmDo3xJRyN5iEWvTDdnQ==,type:str]
    gf_security_admin_password: ENC[AES256_GCM,data:1R9QC7TIkJ1PzcimtQ==,iv:Urfy8JxuYBTqUBtCftXEVLb2WqqK/haASV+jfYcsmmI=,tag:trx7f7U5qihoTxO2qOPgbg==,type:str]

    lastmodified: "2023-04-21T06:45:56Z"
    mac: ENC[AES256_GCM,data:D3ee/i0IIw20jS4d95ASse5VcRgxHZMOMkAJtoHb3U4OMKhNwnh5EbUQTuAgsM7+Bm1R2v5AiReWdqItaabNPYN3dXcIZERLmeY2hICWUQAVLIXxcYgXt9nQT3euakgHFsQ0TjLESbo/lAjJ/mRPpbeWVPGWRhahcSDyml8OT9M=,iv:cSIcbMPGoJ1yQ64/b3sQtbgqQkOlkRwScdqpHoioRTw=,tag:ztG5YX9epnUs3D8qscsK5g==,type:str]
   
    encrypted_regex: ^(data|stringData|caBundle)$
    version: 3.7.3